apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceapp-deployment
  labels:
    app: juiceapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juiceapp
  template:
    metadata:
      labels:
        app: juiceapp
    spec:
      containers:
      - name: juiceapp
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000
        # env:
        # - name: USER_NAME
        #   valueFrom: 
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: mongo-user
        # - name: USER_PWD
        #   valueFrom: 
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: mongo-password
        # - name: DB_URL
        #   valueFrom: 
        #     configMapKeyRef:
        #       name: mongo-config
        #       key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: juiceapp-service
spec:
  type: NodePort
  selector:
    app: juiceapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100