
name: Deploy Terraform to AWS Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    name: Deploy Terraform to Multiple Environments
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initial Terraform
        run: terraform init

      - name: Initial Plan
        run: terraform plan
      - name: Scan Terraform Codes
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: "--report, --severity-threshold=high"
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      # - name: Initial Apply
      #   run: terraform apply --auto-approve
