
name: Deploy Terraform to AWS Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
env: 
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  tf-init:
    name: Deploy Terraform to Multiple Environments
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initial Terraform
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

      - name: Initial Plan
        run: terraform plan
  tf-plan:
    needs: tf-init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initial Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
  
  tf-scan:
    needs: tf-plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Scan Terraform Codes
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # with:
        #   args: --report
        continue-on-error: true
     

      # - name: Upload result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: snyk.sarif

      # - name: Initial Apply
      #   run: terraform apply --auto-approve
