
name: Deploy Terraform to AWS Dev

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env: 
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  tf-init:
    name: Deploy Terraform to Multiple Environments
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initial Terraform
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate
  tf-plan:
    needs: tf-init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initial Terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color
  
  tf-scan:
    needs: tf-plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Scan Terraform Codes
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # with:
        #   args: --report
        continue-on-error: true

  tf-apply:
    needs: tf-scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initial Terraform
        run: terraform init

      - name: Terraform Plan
        run: echo "Terraform Apply Successfully"

    
